### ISSUE TITLE
EOL this ?

### ISSUE THREAD

**Issue by Lctrs** [flathub/org.freedesktop.Sdk.Extension.php74#12]
Few reasons for this : 
- not maintained very often
- I don't use it anymore for a long time
- Not extensible (not possible to add custom PHP extensions for exemple)
- It's possible to call host PHP within flatpak

**Comment by p1u3o** [comment]
I still use this, I've never had much success with calling host php from inside a flatpak and I'd rather keep my host clean.

**Comment by Lctrs** [comment]
Fair enough.
