### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by ArnaudLier** [flathub/org.freedesktop.Sdk.Extension.php74#99]
Hello! Support for PHP 8.1 would be greatly useful! Do you plan to make an extension for it?

**Comment by cthu1hoo** [comment]
I'd like to upvote this request. Not having recent PHP SDK limits vscode + flatpak PHP development to 7.4 which is positively ancient and suboptimal for many reasons.

**Comment by cthu1hoo** [comment]
Here's a 8.0.17 SDK: https://github.com/cthu1hoo/org.freedesktop.Sdk.Extension.php80

I'll try to make a latest 8.1 one when I have some free time, my priority was 8.0 because that's what I'm shipping for my apps.

Edit: https://github.com/cthu1hoo/org.freedesktop.Sdk.Extension.php81

I'd rather not maintain those myself in perpetuity so I'd appreciate those being added to Flathub.

**Comment by francoism90** [comment]
Hopefully this can be pushed soon. Most (web)apps should target at least PHP 8.0 now, however I do understand supporting <7.4 versions as well.

**Comment by cthu1hoo** [comment]
@francoism90 I don't really use flatpak (nor desktop linux) at the moment so someone else will have to push this to flathub. it could be you! :)

**Comment by defaultpage** [comment]
I'm plan to add PHP 8.0-8.2 on current week (as separated flatpak repo).

UPD: You could use this repos (Sdk 22.08, 21.08, 20.08):
[artemmolotov/org.freedesktop.Sdk.Extension.php80](https://github.com/artemmolotov/org.freedesktop.Sdk.Extension.php80)
[artemmolotov/org.freedesktop.Sdk.Extension.php81](https://github.com/artemmolotov/org.freedesktop.Sdk.Extension.php81)
[artemmolotov/org.freedesktop.Sdk.Extension.php82](https://github.com/artemmolotov/org.freedesktop.Sdk.Extension.php82)

**Comment by francoism90** [comment]
https://github.com/francoism90/org.freedesktop.Sdk.Extension.php81

However it doesn't work, because of a missing libaspell, and it also doesn't get installed to lib/ask, is that normal?

**Comment by Lctrs** [comment]
Proposed flathub package for PHP 8.2 : https://github.com/flathub/flathub/pull/4155
